export const data = [
    {
        id: 1,
        img: 'img/sugar.jpg',
        alt: 'sugar: a beauty or beast',
        description: "Sugar: A Beauty or Beast by NutriHub",
        link: "https://realnutrihub.blogspot.com/2023/10/sugar-beauty-or-beast.html?m=1",
        title: "Sugar"
    },
    {
        id: 2,
        img: 'img/water.jpeg',
        alt: 'HEALTH AND WELLNESS; HYDRATION',
        description: "Health  and Wellness; Hydration by NutriHub.",
        link: "https://realnutrihub.blogspot.com/2023/07/health-and-wellness-hydration.html?m=1",
        title: "Hydration"


    },
    {
        id: 3,
        img: 'img/orange.jpeg',
        alt: 'Vitamin C in orange for daily Vitamin C intake',
        description: "Vitamin C in orange for daily Vitamin C intake",
        link: "https://shukreed0207.wixsite.com/healthynourishment-1/post/vitamin-c-in-orange-for-daily-vitamin-c-intake",
        title: "Vitamin C"
    },
    {
        id: 4,
        img: 'img/feed.jpeg',
        alt: 'Exclusive Breastfeeding : Optimal Breastfeeding Postures',
        description: "Exclusive Breastfeeding : Optimal Breastfeeding Postures.",
        link: "https://shukreed0207.wixsite.com/healthynourishment-1/post/exclusive-breastfeeding-optimal-breastfeeding-postures",
        title: "Breast feeding"
    },
    {
        id: 5,
        img: 'img/athlete.png',
        alt: '10 AMAZING NUTRITION TIPS FOR ATHLETES',
        description: "10 AMAZING NUTRITION TIPS FOR ATHLETES by NutriHub",
        link: "https://realnutrihub.blogspot.com/2022/10/10-amazing-nutrition-tips-for-athletes.html?m=1",
        title: "Athlete"
    }
]


export const altdata = [
    {
        foodID: 1,
        foodName: "Apple",
        foodType: "Fruit",
        description: "Apples are crunchy and juicy fruits with a slightly sweet and refreshing flavor. They come in various colors such as red, green, and yellow, each with its own unique taste and texture. Apples are rich in fiber, which aids digestion, and are a good source of vitamin C, promoting a healthy immune system. They also contain antioxidants, which help reduce the risk of chronic diseases.",
        imageURL: "https://example.com/apple.jpg",
        prominent_nutrient: "Vitamin C",
        unit: "mg",
        foodNutrient: {
            "ASH(g)": 0.14,
            "BETA_CAROTENE(mcg)": 27,
            "CALCIUM(mg)": 6,
            "CARBOHYDATE(g)": 14.06,
            "COPPER(mg)": 0.027,
            "ENERGY(KCal)": 63.72,
            "ENERGY(KJ)": 269.41,
            "FAT(g)": 0.2,
            "FIBRE(g)": 2.3,
            "FOLIC_ACID(mcg)": 3,
            "IRON(mg)": 0.11,
            "MAGANESE(mg)": 0.034,
            "MAGNESSIUM(mg)": 5,
            "NIACIN(mg)": 0.075,
            "PHOSPHORUS(mg)": 12,
            "POTASSIUM(mg)": 104,
            "PROTEIN(g)": 0.27,
            "RIBOFLAVIN(mg)": 0.025,
            "SODIUM(mg)": 1,
            "THIAMIN(mg)": 0.015,
            "VIT E(mg)": 0.24,
            "VIT_A_RAE_mcg": 3,
            "VIT_B6(mg)": 0.034,
            "WATER(g)": 85.33,
            "ZINC(mg)": 0.04
        },
        alternativeID: 1,
        alternativeFoodName: "Orange",
        alternativeDescription: "Oranges are citrus fruits known for their bright orange color and tangy-sweet flavor. They are packed with vitamin C, essential for collagen production and immune health. Oranges also provide fiber, aiding digestion, and potassium, important for heart health and muscle function.",
        alternativeImageURL: "https://example.com/orange.jpg",
        alternativeNutrient: "Vitamin C",
        alternativeFoodType: "Fruit",
        altfoodNutrient: {
            "ASH(g)": 0.44,
            "BETA_CAROTENE(mcg)": 373.8,
            "CALCIUM(mg)": 40,
            "CARBOHYDATE(g)": 11.75,
            "COPPER(mg)": 0.045,
            "ENERGY(KCal)": 56.64,
            "ENERGY(KJ)": 239.37,
            "FAT(g)": 0.12,
            "FIBRE(g)": 2.4,
            "FOLIC_ACID(mcg)": 30,
            "IRON(mg)": 0.1,
            "MAGANESE(mg)": 0.025,
            "MAGNESSIUM(mg)": 10,
            "NIACIN(mg)": 0.282,
            "PHOSPHORUS(mg)": 14,
            "POTASSIUM(mg)": 181,
            "PROTEIN(g)": 0.94,
            "RIBOFLAVIN(mg)": 0.04,
            "THIAMIN(mg)": 0.087,
            "VIT E(mg)": 0.18,
            "VIT_A_RAE_mcg": 11,
            "VIT_B6(mg)": 0.06,
            "VIT_C(mg)": 51.9,
            "WATER(g)": 86.75,
            "ZINC(mg)": 0.07
        }
    },
    // {
    //     foodID: 2,
    //     foodName: "Spinach",
    //     foodType: "Vegetable",
    //     description: " Spinach is a leafy green vegetable with a delicate texture and a mild, slightly sweet taste. It is exceptionally nutritious, being rich in iron, which is essential for the production of hemoglobin and oxygen transport in the blood. Spinach is also high in calcium, promoting bone health, and vitamin C, supporting immune function. Additionally, it contains antioxidants like lutein and zeaxanthin, which are beneficial for eye health",
    //     imageURL: "https://example.com/spinach.jpg",
    //     prominent_nutrient: "Iron",
    //     unit: "mg",
    //     foodNutrient: {
    //         "ASH(g)": 2.22,
    //         "CALCIUM(mg)": 112.077,
    //         "CARBOHYDATE(g)": 2.81,
    //         "ENERGY(KCal)": 41.247,
    //         "ENERGY(KJ)": 173.917,
    //         "FAT(g)": 0.49,
    //         "FIBRE(g)": 1.538,
    //         "IRON(mg)": 13.047,
    //         "MAGNESSIUM(mg)": 42.6,
    //         "PHOSPHORUS(mg)": 37.365,
    //         "POTASSIUM(mg)": 224.333,
    //         "PROTEIN(g)": 5.63,
    //         "SODIUM(mg)": 168.5,
    //         "VIT_C(mg)": 133.75,
    //         "WATER(g)": 85.652
    //     },
    //     alternativeID: 2,
    //     alternativeFoodName: "Kale",
    //     alternativeDescription: "Kale is a nutrient-dense leafy green vegetable characterized by its curly leaves and earthy flavor. It is packed with vitamins and minerals, particularly iron, important for red blood cell production, and calcium, essential for bone health. Kale is also a good source of vitamin C, supporting immune function, and fiber, aiding digestion.",
    //     alternativeImageURL: "https://example.com/kale.jpg",
    //     alternativeNutrient: "Iron",
    //     alternativeFoodType: "Vegetable",
    //     altfoodNutrient: []
    // },
    // {
    //     foodID: 3,
    //     foodName: "Broccoli",
    //     foodType: "Vegetable",
    //     description: " Broccoli is a cruciferous vegetable with a firm texture and a slightly bitter taste. It is rich in fiber, promoting digestive health, and vitamin C, boosting immune function and collagen production. Broccoli also contains sulforaphane, a compound with anti-cancer properties, and is high in antioxidants like beta-carotene and quercetin, which help reduce inflammation and oxidative stress.",
    //     imageURL: "https://example.com/spinach.jpg",
    //     prominent_nutrient: "Fiber, Vitamin C",
    //     unit: "mg",
    //     foodNutrient: [],
    //     alternativeID: 3,
    //     alternativeFoodName: "Spinach",
    //     alternativeDescription: " Spinach is a leafy green vegetable with a delicate texture and a mild, slightly sweet taste. It is exceptionally nutritious, being rich in iron, which is essential for the production of hemoglobin and oxygen transport in the blood. Spinach is also high in calcium, promoting bone health, and vitamin C, supporting immune function. Additionally, it contains antioxidants like lutein and zeaxanthin, which are beneficial for eye health",
    //     alternativeImageURL: "https://example.com/kale.jpg",
    //     alternativeNutrient: "Iron, Vitamin C",
    //     alternativeFoodType: "Vegetable",
    //     altfoodNutrient: {
    //         "ASH(g)": 2.22,
    //         "CALCIUM(mg)": 112.077,
    //         "CARBOHYDATE(g)": 2.81,
    //         "ENERGY(KCal)": 41.247,
    //         "ENERGY(KJ)": 173.917,
    //         "FAT(g)": 0.49,
    //         "FIBRE(g)": 1.538,
    //         "IRON(mg)": 13.047,
    //         "MAGNESSIUM(mg)": 42.6,
    //         "PHOSPHORUS(mg)": 37.365,
    //         "POTASSIUM(mg)": 224.333,
    //         "PROTEIN(g)": 5.63,
    //         "SODIUM(mg)": 168.5,
    //         "VIT_C(mg)": 133.75,
    //         "WATER(g)": 85.652
    //     }
    // },
    {
        foodID: 4,
        foodName: "Plum",
        foodType: "Fruit",
        description: "Plums are small, juicy fruits with a smooth skin and a sweet-tart flavor. They come in a variety of colors, including red, purple, and yellow. Plums are rich in antioxidants, particularly vitamin C, which helps protect cells from damage caused by free radicals. They also contain fiber, promoting digestive health, and potassium, important for heart health and blood pressure regulation.",
        imageURL: "https://example.com/plum.jpg",
        prominent_nutrient: "Vitamin C",
        unit: "mg",
        foodNutrient: {
            "ENERGY(KCal)": 112,
            "WATER(g)": 70.1,
            "PROTEIN(g)": 0.4,
            "FAT(g)": 0.2,
            "CARBOHYDRATE(g)": 26.4,
            "FIBRE(g)": 1.4,
            "ASH(g)": 1.5,
            "CALCIUM(mg)": 25,
            "IRON(mg)": 1.1,
            "MAGNESIUM(mg)": 21,
            "PHOSPHORUS(mg)": 53,
            "POTASSIUM(mg)": 637,
            "SODIUM(mg)": 8,
            "VIT C(mg)": 10
        },
        alternativeID: 4,
        alternativeFoodName: "Apple",
        alternativeDescription: "Apples are crisp, sweet, and juicy fruits with a variety of flavors and colors.Apples are crunchy and juicy fruits with a slightly sweet and refreshing flavor. They come in various colors such as red, green, and yellow, each with its own unique taste and texture. Apples are rich in fiber, which aids digestion, and are a good source of vitamin C, promoting a healthy immune system. They also contain antioxidants, which help reduce the risk of chronic diseases.",
        alternativeImageURL: "https://example.com/apple.jpg",
        alternativeNutrient: "Vitamin C",
        alternativeFoodType: "Fruit",
        altfoodNutrient:  {
            "ASH(g)": 0.14,
            "BETA_CAROTENE(mcg)": 27,
            "CALCIUM(mg)": 6,
            "CARBOHYDATE(g)": 14.06,
            "COPPER(mg)": 0.027,
            "ENERGY(KCal)": 63.72,
            "ENERGY(KJ)": 269.41,
            "FAT(g)": 0.2,
            "FIBRE(g)": 2.3,
            "FOLIC_ACID(mcg)": 3,
            "IRON(mg)": 0.11,
            "MAGANESE(mg)": 0.034,
            "MAGNESSIUM(mg)": 5,
            "NIACIN(mg)": 0.075,
            "PHOSPHORUS(mg)": 12,
            "POTASSIUM(mg)": 104,
            "PROTEIN(g)": 0.27,
            "RIBOFLAVIN(mg)": 0.025,
            "SODIUM(mg)": 1,
            "THIAMIN(mg)": 0.015,
            "VIT E(mg)": 0.24,
            "VIT_A_RAE_mcg": 3,
            "VIT_B6(mg)": 0.034,
            "WATER(g)": 85.33,
            "ZINC(mg)": 0.04
        },
    },
    {
        foodID: 5,
        foodName: "Egg",
        foodType: "Protein",
        description: "Eggs are versatile and nutritious protein sources packed with essential nutrients. They are rich in high-quality protein, providing all the essential amino acids necessary for muscle repair and growth. Eggs also contain vitamins such as vitamin D, important for bone health, and vitamin B12, essential for nerve function. Additionally, they are a good source of minerals like iron, promoting red blood cell production, and zinc, supporting immune function.",
        imageURL: "https://example.com/egg.jpg",
        prominent_nutrient: "Protein",
        unit: "g",
        foodNutrient: {
            "ASH(g)": 2.193,
            "BETA_CAROTENE(mcg)": 11,
            "CALCIUM(mg)": 82.8,
            "CARBOHYDATE(g)": 1.373,
            "COPPER(mg)": 0.013,
            "ENERGY(KCal)": 194.93,
            "ENERGY(KJ)": 811.49,
            "FAT(g)": 13.57,
            "FOLIC_ACID(mcg)": 44,
            "IRON(mg)": 2.03,
            "MAGANESE(mg)": 0.026,
            "MAGNESSIUM(mg)": 10,
            "NIACIN(mg)": 0.064,
            "PHOSPHORUS(mg)": 294.7,
            "POTASSIUM(mg)": 184.733,
            "PROTEIN(g)": 16.827,
            "RETINOL(mcg)": 148,
            "RIBOFLAVIN(mg)": 0.513,
            "SODIUM(mg)": 189.933,
            "THIAMIN(mg)": 0.066,
            "VIT D(mcg)": 2.2,
            "VIT E(mg)": 1.03,
            "VITB_12(mcg)": 1.11,
            "VIT_A_RAE_mcg": 149,
            "VIT_B6(mg)": 0.121,
            "WATER(g)": 66.107,
            "ZINC(mg)": 1.817
        },
        alternativeID: 5,
        alternativeFoodName: "Fish",
        alternativeDescription: "Fish is a nutrient-rich protein source known for its omega-3 fatty acids, which are beneficial for heart health and brain function. It is also high in high-quality protein, essential for muscle repair and growth. Fish varieties like salmon and tuna are rich in vitamins such as vitamin D, important for bone health, and minerals like selenium, supporting antioxidant defense systems.",
        alternativeImageURL: "https://example.com/fish.jpg",
        alternativeNutrient: "Protein, Omega-3",
        alternativeFoodType: "Protein",
        altfoodNutrient: {
            "CALCIUM(mg)": 14,
            "ENERGY(KCal)": 128.45,
            "ENERGY(KJ)": 542.6,
            "FAT(g)": 2.65,
            "FOLIC_ACID(mcg)": 6,
            "IRON(mg)": 0.69,
            "Id": 235,
            "MAGNESSIUM(mg)": 34,
            "NIACIN(mg)": 4.745,
            "PHOSPHORUS(mg)": 204,
            "POTASSIUM(mg)": 380,
            "PROTEIN(g)": 26.15,
            "REFID": "13b",
            "RIBOFLAVIN(mg)": 0.073,
            "SODIUM(mg)": 56,
            "THIAMIN(mg)": 0.093,
            "VIT D(mcg)": 3.7,
            "VIT E(mg)": 0.79,
            "VITB_12(mcg)": 1.86,
            "VIT_B6(mg)": 0.123,
            "WATER(g)": 71.59,
            "ZINC(mg)": 0.41
        }
    },
    // {
    //     foodID: 6,
    //     foodName: "Tofu",
    //     foodType: "Protein",
    //     description: "Tofu, also known as bean curd, is a soy-based protein alternative with a versatile texture. It is made by coagulating soy milk and pressing the resulting curds into soft, white blocks. Tofu is a staple ingredient in many cuisines, particularly in Asian dishes. It has a subtle flavor that easily absorbs the flavors of other ingredients in a dish. Tofu is a rich source of plant-based protein, making it an excellent option for vegetarians and vegans. It is also low in calories and contains no cholesterol, making it a heart-healthy choice.",
    //     imageURL: "https://example.com/tofu.jpg",
    //     prominent_nutrient: "Protein",
    //     unit: "g",
    //     foodNutrient: [],
    //     alternativeID: 6,
    //     alternativeFoodName: "Egg",
    //     alternativeDescription: "Eggs are versatile and nutritious protein sources packed with essential nutrients. They are rich in high-quality protein, providing all the essential amino acids necessary for muscle repair and growth. Eggs also contain vitamins such as vitamin D, important for bone health, and vitamin B12, essential for nerve function. Additionally, they are a good source of minerals like iron, promoting red blood cell production, and zinc, supporting immune function.",
    //     alternativeImageURL: "https://example.com/egg.jpg",
    //     alternativeNutrient: "Protein",
    //     alternativeFoodType: "Protein",
    //     altfoodNutrient: {
    //         "ASH(g)": 2.193,
    //         "BETA_CAROTENE(mcg)": 11,
    //         "CALCIUM(mg)": 82.8,
    //         "CARBOHYDATE(g)": 1.373,
    //         "COPPER(mg)": 0.013,
    //         "ENERGY(KCal)": 194.93,
    //         "ENERGY(KJ)": 811.49,
    //         "FAT(g)": 13.57,
    //         "FOLIC_ACID(mcg)": 44,
    //         "IRON(mg)": 2.03,
    //         "MAGANESE(mg)": 0.026,
    //         "MAGNESSIUM(mg)": 10,
    //         "NIACIN(mg)": 0.064,
    //         "PHOSPHORUS(mg)": 294.7,
    //         "POTASSIUM(mg)": 184.733,
    //         "PROTEIN(g)": 16.827,
    //         "RETINOL(mcg)": 148,
    //         "RIBOFLAVIN(mg)": 0.513,
    //         "SODIUM(mg)": 189.933,
    //         "THIAMIN(mg)": 0.066,
    //         "VIT D(mcg)": 2.2,
    //         "VIT E(mg)": 1.03,
    //         "VITB_12(mcg)": 1.11,
    //         "VIT_A_RAE_mcg": 149,
    //         "VIT_B6(mg)": 0.121,
    //         "WATER(g)": 66.107,
    //         "ZINC(mg)": 1.817
    //     },
    // },
    {
        foodID: 7,
        foodName: "Lentils",
        foodType: "Legume",
        description: "Lentils are legumes packed with protein and fiber. They come in various colors, including green, brown, red, and black, and have been a dietary staple in many cultures for centuries. Lentils have a slightly nutty flavor and a firm texture when cooked. They are rich in plant-based protein, making them an excellent meat alternative for vegetarians and vegans. Lentils are also high in dietary fiber, which aids digestion and helps regulate blood sugar levels. Additionally, they are a good source of folate, iron, and other essential nutrients",
        imageURL: "https://example.com/lentils.jpg",
        prominent_nutrient: "Protein, Fiber",
        unit: "g",
        foodNutrient:{
            "ENERGY(KJkcal)": "0.07",
            "WATER(g)": "0.18",
            "PROTEIN(g)": "0.15",
            "FAT(g)": "0.04",
            "CARBOHYDRATE(g)": "89",
            "SATURATED FAT (g)": "0.05",
            "MONOUNSATURATED FAT (g)": "0.07",
            "POLYUNSAT FAT (g)": "0.18",
            "LINOLEIC ACID (g)": "0.15",
            "ALPHA-LINOLENIC ACID (g)": "0.04",
            "PHYTATE (mg)": "89",
            "CALCIUM(mg)": "17",
            "IRON(mg)": "1.6",
            "MAGNESIUM(mg)": "28",
            "PHOSPHORUS(mg)": "92",
            "POTASSIUM(mg)": "163",
            "SODIUM(mg)": "12",
            "ZINC(mg)": "0.91",
            "COPPER(mg)": "0.22",
            "VIT A RE(mcg)": "1",
            "BETA-CAROTENE(mcg)": "5",
            "VIT D (mcg)": "201",
            "VIT E (mg)": "6.5",
            "THIAMINE (mg)": "247",
            "RIBOFLAVIN (mg)": "566",
            "NIACIN EQUIV (mg)": "1 750",
            "NIACIN (mg)": "5",
            "TRYPTOPHAN (mg)": "4.75",
            "VIT B6 (mg)": "1.49",
            "VIT C (mg)": "3"
        },
        alternativeID: 7,
        alternativeFoodName: "Beans (boiled)",
        alternativeDescription: "Boiled beans are a nutritious source of protein and fiber. They come in various varieties such as black beans, kidney beans, and chickpeas, each offering its own unique taste and texture. Beans are rich in plant-based protein, making them an excellent meat alternative for vegetarians and vegans. They are also high in dietary fiber, which aids digestion and helps lower cholesterol levels. Additionally, beans are packed with vitamins and minerals, including folate, iron, and potassium, promoting overall health.",
        alternativeImageURL: "https://example.com/beans.jpg",
        alternativeNutrient: "Protein, Fiber",
        alternativeFoodType: "Legume",
        altfoodNutrient: {
            "ASH(g)": 2.419,
            "BETA_CAROTENE(mcg)": 126,
            "CALCIUM(mg)": 6.19,
            "CARBOHYDATE(g)": 21.52,
            "COPPER(mg)": 3.96,
            "ENERGY(KCal)": 147.56,
            "ENERGY(KJ)": 623.858,
            "FAT(g)": 0.496,
            "FIBRE(g)": 5.3,
            "FOLIC_ACID(mcg)": 77,
            "IRON(mg)": 1.24,
            "MAGANESE(mg)": 1.54,
            "MAGNESSIUM(mg)": 5.25,
            "NIACIN(mg)": 0.7,
            "POTASSIUM(mg)": 0.91,
            "PROTEIN(g)": 11.605,
            "RIBOFLAVIN(mg)": 0.04,
            "SODIUM(mg)": 6.7,
            "THIAMIN(mg)": 0.17,
            "VIT E(mg)": 0.17,
            "VIT_B6(mg)": 0.09,
            "VIT_C(mg)": 0.2,
            "WATER(g)": 63.525,
            "ZINC(mg)": 0.78
        }        
    },
    {
        foodID: 9,
        foodName: "Milk",
        foodType: "Dairy",
        description: "Milk is a nutrient-rich liquid produced by mammals to nourish their young. It is a rich source of calcium, which is essential for bone health and teeth strength. Milk also provides high-quality protein, containing all the essential amino acids necessary for muscle repair and growth. It is fortified with vitamin D, which helps the body absorb calcium and supports immune function. Additionally, milk contains vitamins A and B12, riboflavin, and phosphorus, contributing to overall health and well-being.",
        imageURL: "https://example.com/milk.jpg",
        prominent_nutrient: "Calcium",
        unit: "mg",
        foodNutrient: {
            "ENERGY (kcal)": "0.98",
            "WATER (g)": "0.12",
            "PROTEIN (g)": "0.05",
            "FAT (g)": "0.01",
            "CHOLESTEROL (mg)": "14",
            "SAT FA(g)": "2.11",
            "MONOUNSATURATED FAT (G)": "0.98",
            "POLYUNSAT FA (g)": "0.12",
            "LINOLEIC ACID (g)": "0.05",
            "ALPHA-LINOLENIC ACID (g)": "0.01",
            "CALCIUM(mg)": "119",
            "IRON(mg)": "0.1",
            "MAGNESIUM(mg)": "12",
            "PHOSPHORUS(mg)": "111",
            "POTASSIUM(mg)": "147",
            "SODIUM(mg)": "45",
            "ZINC(mg)": "0.63",
            "COPPER(mg)": "0.01",
            "VIT A RE(mcg)": "43",
            "VIT A RAE(mcg)": "42",
            "RETINOL(mcg)": "40",
            "BETA-CAROTENEEQUIV(mcg)": "17",
            "VIT D (mcg)": "0.1",
            "VIT E (mg)": "0.17",
            "THIAMINE (mg)": "0.04",
            "RIBOFLAVIN (mg)": "0.27",
            "NIACIN EQUIV (mg)": "0.8",
            "NIACIN (mg)": "0.1",
            "TRYPTOPHAN (mg)": "39",
            "VIT B6 (mg)": "0.03",
            "FOLATE (mcg)": "8",
            "FOLATE EQUIV (mcg)": "8",
            "VIT B12 (mcg)": "0.59"
        },
        alternativeID: 9,
        alternativeFoodName: "Egg",
        alternativeDescription: "Eggs are versatile and nutritious protein sources packed with essential nutrients. They are rich in high-quality protein, providing all the essential amino acids necessary for muscle repair and growth. Eggs also contain vitamins such as vitamin D, important for bone health, and vitamin B12, essential for nerve function. Additionally, they are a good source of minerals like iron, promoting red blood cell production, and zinc, supporting immune function.",
        alternativeImageURL: "https://example.com/egg.jpg",
        alternativeNutrient: "Protein",
        alternativeFoodType: "Protein",
        altfoodNutrient: {
            "ASH(g)": 2.193,
            "BETA_CAROTENE(mcg)": 11,
            "CALCIUM(mg)": 82.8,
            "CARBOHYDATE(g)": 1.373,
            "COPPER(mg)": 0.013,
            "ENERGY(KCal)": 194.93,
            "ENERGY(KJ)": 811.49,
            "FAT(g)": 13.57,
            "FOLIC_ACID(mcg)": 44,
            "IRON(mg)": 2.03,
            "MAGANESE(mg)": 0.026,
            "MAGNESSIUM(mg)": 10,
            "NIACIN(mg)": 0.064,
            "PHOSPHORUS(mg)": 294.7,
            "POTASSIUM(mg)": 184.733,
            "PROTEIN(g)": 16.827,
            "RETINOL(mcg)": 148,
            "RIBOFLAVIN(mg)": 0.513,
            "SODIUM(mg)": 189.933,
            "THIAMIN(mg)": 0.066,
            "VIT D(mcg)": 2.2,
            "VIT E(mg)": 1.03,
            "VITB_12(mcg)": 1.11,
            "VIT_A_RAE_mcg": 149,
            "VIT_B6(mg)": 0.121,
            "WATER(g)": 66.107,
            "ZINC(mg)": 1.817
        },
    },
    {
        foodID: 10,
        foodName: "Boiled Rice",
        foodType: "Grain",
        description: "Boiled rice is a staple food rich in carbohydrates. It is made from the seeds of the Oryza sativa plant and is a dietary staple for more than half of the world's population. Boiled rice comes in various varieties, including white, brown, and wild rice, each with its own unique taste and texture. It is a rich source of complex carbohydrates, providing sustained energy for the body. Boiled rice is also low in fat and sodium and contains no cholesterol, making it a heart-healthy choice. Additionally, it is gluten-free, making it suitable for individuals with gluten intolerance or celiac disease.",
        imageURL: "https://example.com/rice.jpg",
        prominent_nutrient: "Carbohydrates",
        unit: "g",
        foodNutrient: {
            "ASH(g)": 0.665,
            "BETA_CAROTENE(mcg)": 34,
            "CALCIUM(mg)": 4.195,
            "CARBOHYDATE(g)": 29.637,
            "COPPER(mg)": 1.11,
            "ENERGY(KCal)": 132.727,
            "ENERGY(KJ)": 563.447,
            "FAT(g)": 0.253,
            "FIBRE(g)": 0.65,
            "FOLIC_ACID(mcg)": 5.5,
            "IRON(mg)": 0.73,
            "MAGNESSIUM(mg)": 8.13,
            "NIACIN(mg)": 0.4,
            "PHOSPHORUS(mg)": 38,
            "POTASSIUM(mg)": 34,
            "PROTEIN(g)": 2.65,
            "RIBOFLAVIN(mg)": 0.15,
            "SODIUM(mg)": 3.267,
            "THIAMIN(mg)": 0.01,
            "VIT E(mg)": 0.04,
            "VIT_B6(mg)": 0.04,
            "WATER(g)": 67.65,
            "ZINC(mg)": 0.635
        },
        alternativeID: 10,
        alternativeFoodName: "Whole wheat Bread",
        alternativeDescription: "Whole wheat bread is a common source of carbohydrates. It is made from whole grains, including wheat, which are rich in fiber, vitamins, and minerals. Unlike white bread, which is made from refined grains, whole wheat bread retains the bran and germ of the grain, making it a healthier option. Whole wheat bread is a good source of complex carbohydrates, providing sustained energy for the body. It is also high in dietary fiber, which aids digestion and helps regulate blood sugar levels. Additionally, whole wheat bread contains vitamins and minerals such as iron, magnesium, and B vitamins, contributing to overall health and well-being.",
        alternativeImageURL: "https://example.com/bread.jpg",
        alternativeNutrient: "Carbohydrates",
        alternativeFoodType: "Grain",
        altfoodNutrient: {
            "ASH(g)": 1.84,
            "BETA_CAROTENE(mcg)": 2,
            "CALCIUM(mg)": 89.841,
            "CARBOHYDATE(g)": 51.761,
            "COPPER(mg)": 0.25,
            "ENERGY(KCal)": 281.806,
            "ENERGY(KJ)": 1191.325,
            "FAT(g)": 4.014,
            "FIBRE(g)": 2.669,
            "FOLIC_ACID(mcg)": 39,
            "IRON(mg)": 4.07,
            "MAGNESSIUM(mg)": 53.332,
            "NIACIN(mg)": 3,
            "PHOSPHORUS(mg)": 171.368,
            "POTASSIUM(mg)": 172.729,
            "PROTEIN(g)": 8.324,
            "RIBOFLAVIN(mg)": 0.06,
            "SODIUM(mg)": 350.156,
            "THIAMIN(mg)": 0.3,
            "VIT E(mg)": 0.76,
            "VIT_B6(mg)": 0.473,
            "WATER(g)": 32.223,
            "ZINC(mg)": 1.5
        }
        
    },
]

